version: "3.3"
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      - back_net
  ui:
    build: ./ui
    image: ${USER}/ui:$VER_UI
    ports:
      - ${EXT_PORT}:${INT_PORT}/tcp
    networks:
      - front_net
  post:
    build: ./post-py
    image: ${USER}/post:${VER_POST}
    networks:
      - front_net
      - back_net
  comment:
    build: ./comment
    image: ${USER}/comment:${VER_COMMENT}
    networks:
      - front_net
      - back_net

volumes:
  post_db:

networks:
  back_net:
  front_net:
